version: '3'
services:
  web:
    build: ./src/
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost 8000 || exit -1
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy


  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    networks:
      - backend

  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - backend

  parser:
    build: ./parser/
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - backend

  test_server:
    build: ./web_server/
    ports:
      - "5000:5000"
    networks:
      - backend


networks:
  backend:
    driver: bridge
