name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:

  flake8_check:
    runs-on: ubuntu-latest
    env:
      report_path: flake_report
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Create folder for artifact
        run: |
          mkdir ${{ env.report_path }}
      - name: Analysing the code with flake8
        run: flake8 --ignore=E501,E226


  mypy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Check src
        run: |
          mypy ./src --ignore-missing-import, --disable-error-code union-attr, --disable-error-code call-arg